version: "2"

volumes:
  mysql:
  project:
  results:

services:
  mysql:
    image: lecodes/server_mysql:latest
    build: images/mysql
    network_mode: bridge
    volumes:
     - "mysql:/var/lib/mysql"
    environment: 
     - MYSQL_ROOT_PASSWORD=
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  makeproject:
    image: lecodes/server_makeproject:latest
    build: 
      context: images/makeproject
      dockerfile: Dockerfile
    hostname: boincserver
    network_mode: bridge
    links: 
     - mysql
    volumes:
     - "project:/root/project.dst"

  apache:
    image: lecodes/server_apache:latest
    build: 
      context: images/apache
      dockerfile: Dockerfile
    hostname: boincserver
    network_mode: bridge
    links:
     - mysql
    volumes: 
     - "project:/root/project"
     - "results:/results"
     - "/var/run/docker.sock:/var/run/docker.sock"
    ports: 
     - "127.0.0.1:80:80"
    tty: true


